### ISSUE TITLE
node-red tries to invoke npm update?

### ISSUE THREAD

**Issue by Loreno10** [node-red/node-red-docker#208] opened 2020-10-28 10:41 UTC
#170 
# What are the steps to reproduce?
Run node-red dockerized without permissions to use `npm update`

### What happens?

This error:

```
> node-red-docker@1.2.2 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/files"
27 Oct 15:55:46 - [info]
Welcome to Node-RED
===================
27 Oct 15:55:46 - [info] Node-RED version: v1.2.2
27 Oct 15:55:46 - [info] Node.js  version: v10.22.1
27 Oct 15:55:46 - [info] Linux 4.15.0-20-generic x64 LE
27 Oct 15:55:46 - [info] Loading palette nodes
27 Oct 15:55:46 - [info] Settings file  : /files/settings.js
27 Oct 15:55:46 - [info] Context store  : 'default' [module=memory]
27 Oct 15:55:46 - [info] User directory : /files
27 Oct 15:55:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
27 Oct 15:55:46 - [info] Flows file     : /files/flows.json
27 Oct 15:55:46 - [info] Creating new flow file
27 Oct 15:55:46 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
27 Oct 15:55:46 - [info] Starting flows
27 Oct 15:55:46 - [info] Started flows
27 Oct 15:55:46 - [info] Server now running at http://127.0.0.1:1880/
27 Oct 15:57:18 - [info] Stopping flows
27 Oct 15:57:18 - [info] Stopped flows
┌──────────────────────────────────────────────┐
│           npm update check failed            │
│     Try running with sudo or get access      │
│     to the local update config store via     │
│ sudo chown -R $USER:$(id -gn $USER) /.config │
└──────────────────────────────────────────────┘
```

### What do you expect to happen?

No `npm update` check. I don't understand why `npm update` even happens in the container? Shouldn't the app just `npm start` with the dependencies being "frozen" at the versions that were available during image build?

### Please tell us about your environment:

[ ] Platform/OS:
Ubuntu 18.04

[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by dceejay** [comment] 2020-10-28 11:00
Closed as 100% duplicate of #209

**Closed by dceejay** 2020-10-28 11:00 UTC
