### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by icanic** [node-red/node-red-docker#48] opened 2017-10-02 15:56 UTC
Greetings!
I have problem with node-red.
I have tried to change timezone in node red but nothing works.
I am running node red on synology NAS.

**Comment by jthomas** [comment] 2017-10-03 08:46
Hello. 

Can you give the steps you used to change the timezone and how you attempted to verify it?

**Comment by mabunixda** [comment] 2017-10-19 20:38
@icanic just map /etc/localtime into the container
`docker run -v /etc/localtime:/etc/localtime `

**Comment by i8beef** [comment] 2018-01-29 22:30
I am running with -TZ="America/New_York" and still my inject nodes seem to only from on GMT.

**Comment by RaymondMouthaan** [comment] 2018-02-13 13:12
Sometimes the host distro has a /etc/timezone while others have /etc/TZ.

One of these should work:

`docker run -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro`

`docker run -v /etc/localtime:/etc/localtime:ro -v /etc/TZ:/etc/timezone:ro` (synology nas)
 
Hope this helps!

**Comment by iuripereira** [comment] 2018-06-24 23:12
I solved this problem locally by running this command

```
sudo npm cache clean
sudo npm install -g --unsafe-perm node-red
```

**Comment by supagold** [comment] 2018-07-27 17:34
Just an update in case anyone is in the same boat as me: For various reasons, I prefer to configure as much as I can within Synology's idiosyncratic docker GUI. @RaymondMouthaan solution works, but the GUI doesn't want to let you browse into that part of the file system to link the synology system files to the container's files.

My work around was to use SSH to symlink /etc/TZ and /etc/localtime into the folder where I keep my node-red config on my data volume. The GUI _also_ doesn't want you to let you link to a symlink, so you'll want to create a dummy files (eg "touch TZ") configure the GUI to point to them, then after you save your config, you can just replace the dummy files with the symlinks, and everything works.

**Comment by jhelmink** [comment] 2018-08-29 06:14
@supagold does the symlink survive a restart?
I'm in the same boat. Would prefer a OOTB solution, like a TZ environment variable like most other containers use,

**Comment by supagold** [comment] 2018-08-29 14:17
@jhelmink I actually didn't think to test that, but I just did a reboot this weekend. It all appears to be working fine. EG doing "cat TZ" on my symlink gives the same output as "cat /etc/TZ" on the host, then doing "cat /etc/timezone" in the container also gives the same output. Functionally, all my nodes still seem to be firing correctly.

I'm not 100% sure if I follow your question on the container data, but I map the data directory the same as my other containers and haven't been having any issues. FWIW, that might be because I don't use the Docker volume that DSM creates? All my docker data lives in a folder on my regular share volume.

**Comment by jhelmink** [comment] 2018-08-29 21:13
FYI to anyone reading this thread. Manually adding a TZ environment variable via the Synology Docker UI and setting your timezone does actually work with the Node Red docker container.

@supagold FYI.
@jthomas I would consider this issue closed.

**Comment by nodecentral** [comment] 2018-09-02 10:02
@jhelmink , I’m using QNAP’s Container Station, which is assume is similar. How exactly did you add a TZ environment variable to an existing docker/container ? Please could you explain the steps

**Comment by nodecentral** [comment] 2018-09-02 10:08
I also tried @iuripereira suggestions, but that did not work for me .

`[/] # docker run -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -e TZ=Europe/London                                                                                                                        
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container`

**Comment by i8beef** [comment] 2018-09-02 19:27
Confirmed, at least for the x86 build, that '-TZ Linux/ZoneName' is sufficient to set the timezone correctly now. Did some research and it looked like the upstream Alpine images (https://github.com/gliderlabs/docker-alpine/issues/136) had a bug around this where they only maintained the tzdata package for installs, but were removing everything (like the /usr/share/zoneinfo files) post distribution blob generation. It looks like they no longer blow that away, which lets the ENV variable work correctly without having to force linking an external copy of those files (the -v /etc/timezone mounts above).

Essentially, without those files it reads the ENV variable, but can't find a matching file in /usr/share/zoneinfo, so I think it falls back to UTC. 

Ergo: An upstream issue that was fixed in the Alpine images.

**Comment by jhelmink** [comment] 2018-09-03 08:16
@nodecentral You might only be able to set variables during the creation process.
There are some things that cannot be edited after creation with Synology (though variables isn't one of them)

**Comment by restalfep** [comment] 2018-10-20 16:13
Update incase anyone else is having trouble with the above also: I finally got it to work by stopping the Node-Red docker in GUI, going in to SSH for DSM, then running:

docker run -it -p 1880:1880 -v /volume1/docker/Node-Red:/data -v /etc/localtime:/etc/localtime:ro -v /etc/TZ:/etc/timezone:ro -e TZ=America/New_York --name nodered8 nodered/node-red-docker:v8

I then deleted the old docker. 

After that it seems you don't need to use SSH anymore, it will appear in your Synology Docker GUI and can be stopped/started, etc from there.  Not sure why the symlink and other solutions didn't work with the existing docker.

**Comment by dirstel** [comment] 2018-12-06 08:41
I had the same issue with the docker image tagged "slim" running on a NUC and ubuntu (latest LTS) as host. None of the above suggested solutions worked for me. 
As a workarround I switched to "latest" image which is of course a lot bigger, but provides the functionality via Environment (docker-compose.yaml).

**Comment by IoTPlay** [comment] 2019-04-09 19:33
Hi, running on `nodered/node-red-docker:0.20.5-v10`, using `-e TZ="Africa/Johannesburg"` in the `docker run` command. I am running the docker on a RPi. When I log into the docker container with `docker exec ...`, running `date` give me `SAST`, South African Standard Time. 
So far so good. But, looking at events raised, to a node-red-dashboard, they are still reported in UTC. 
I thought Node-RED would take the TZ of docker host?

**Comment by IoTPlay** [comment] 2019-04-09 19:42
Hi, I think my fault - using JSONata to transform the date, think I need to go look into it first. Command that I use is `$substring($fromMillis($.timestamp),0,10),` - I think `fromMillis` turns date to UTC.

**Comment by RaymondMouthaan** [comment] 2019-09-30 21:11
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.

**Closed by RaymondMouthaan** 2019-09-30 21:11 UTC

**Comment by unholyhimura** [comment] 2020-09-26 16:27
Hello, on Synology NAS it's possible to use the Docker Application to pass the timezone automatically to the container creation. 
Click in the “Environment” tab and add TZ in the variable & your timezone as the value.

You can follow this guide to see how can you do it.

[https://www.atomicha.com/synology-nas-docker-installing-node-red-part-3-docker-image-configuration/](https://www.atomicha.com/synology-nas-docker-installing-node-red-part-3-docker-image-configuration/)

**Comment by David-Lor** [comment] 2020-09-30 20:48
I confirm that using the "TZ" environment variable seems to be the way to go. I always bind /etc/localtime & /etc/timezone, but that does not seem to work with Node-RED containers.

**Comment by zafrirron** [comment] 2022-02-08 11:19
After wasting some time on this issue:

In dockerized node-red you have 3 time stamps:

1. docker host time
2. docker container time
3. client time

Each can have its own different time zone setting, time update/synch status and current time.

unless youe dicker host is synched and have correct time zone and ntp synched the docker compose time zone environemnt variable will not produce the correct time for the docker container and timestamp inject node will not produce the correct time.

(regardles of the time related volumes mappings).

So first verify your host has the correct time (by issueing a $date command in the host machine environment)
then issue a $date ecommand inside the container bash environment to make sure the times are identical.
 
then on node red canvas create a timestamp inject node connected to the following  function node:

```
var date = new Date();
// Hours part from the timestamp
var hours = date.getHours();
// Minutes part from the timestamp
var minutes = "0" + date.getMinutes();
// Seconds part from the timestamp
var seconds = "0" + date.getSeconds();

// Will display time in 10:30:23 format
var formattedTime = hours + ':' + minutes.substr(-2) + ':' + seconds.substr(-2);

//console.log(formattedTime);
msg.payload = formattedTime;
return msg;  
```
connect debug node and check the time message on the debug console, verify its identical to the container and host time stamp.
