### ISSUE TITLE
Error: EACCES: permission denied, copyfile

### ISSUE THREAD

**Issue by TimoB2005** [node-red/node-red-docker#265] opened 2021-08-03 07:48 UTC
What are the steps to reproduce?
I started node-red in docker with my docker-compose file and my dockerfile

In my Dockerfile i declared that the user node-red should copy the files into the data volume

"USER node-red
COPY ./data /data
COPY ./data/settings.js /usr/src
COPY ./data/flows.json /usr/src"

and in my docker-compose file: volumes: ./data:/data

What happens?
I get the following errors when it starts,

`

> Error: EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'
>                          at Object.copyFileSync (fs.js:1728:3)
>                          at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
>                          at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
>                          at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
>                          at startCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
>                          at handleFilterAndCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
>                          at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
>                          at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:125:20)
>                          at Module._compile (internal/modules/cjs/loader.js:778:30)
>                          at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

`

What do you expect to happen?
My files get copied into the folder data

Please tell us about your environment:
OS: Ubuntu

I know there are many issues about this out there but none of them have fixed my problem...

**Comment by hardillb** [comment] 2021-08-03 07:50
You need to provide a lot more details in the "What are the steps to reproduce?" section.

**Comment by TimoB2005** [comment] 2021-08-03 07:54
> You need to provide a lot more details in the "What are the steps to reproduce?" section.

I updated my steps

**Comment by TimoB2005** [comment] 2021-08-03 07:55
Without the mount it works perfectly

**Comment by hardillb** [comment] 2021-08-03 07:55
And what is the ownership and permissions of the `./data` directory?

**Comment by TimoB2005** [comment] 2021-08-03 07:56
![image](https://user-images.githubusercontent.com/83423736/127979184-3c7f76d5-29bb-4c9f-a65a-f4be1731bdf9.png)

**Comment by hardillb** [comment] 2021-08-03 08:07
Your Dockerfile doesn't make any sense

```
USER node-red
COPY ./data /data
COPY ./data/settings.js /usr/src
COPY ./data/flows.json /usr/src
```

The last 2 lines will put the `settings.js` and `flows.json` into `/usr/src` which will never get used by Noded-RED

It should look like:

```
COPY ./data/settings.js /data/settings.js
COPY ./data/flows.json /data/flows.json
```

Add your full Dockerfile and the docker-compose.yml so we can see everything and not have to guess.

**Comment by TimoB2005** [comment] 2021-08-03 08:16
My docker-compose: https://hastebin.com/kuborutepa.less
My actually Dockerfile: https://hastebin.com/yimaceceto.sql

**Comment by TimoB2005** [comment] 2021-08-03 08:26
> Your Dockerfile doesn't make any sense
> 
> ```
> USER node-red
> COPY ./data /data
> COPY ./data/settings.js /usr/src
> COPY ./data/flows.json /usr/src
> ```
> 
> The last 2 lines will put the `settings.js` and `flows.json` into `/usr/src` which will never get used by Noded-RED
> 
> It should look like:
> 
> ```
> COPY ./data/settings.js /data/settings.js
> COPY ./data/flows.json /data/flows.json
> ```
> 
> Your Dockerfile doesn't make any sense

I did that on purpose to have an save folder

**Comment by hardillb** [comment] 2021-08-03 08:36
All of that works just fine for me.

What are the file permissions and ownership on what is already in the `data` directory?  e.g. is the `settings.js` file also owned by user 1000?

**Comment by TimoB2005** [comment] 2021-08-03 08:39
Thats inside the data folder:
![image](https://user-images.githubusercontent.com/83423736/127985244-69b05879-1f45-489f-8434-5c527d672662.png)

The settings file is also owned by 1000

**Comment by hardillb** [comment] 2021-08-03 08:43
Then the only other different part here is the `start.sh` what's in that?

**Comment by TimoB2005** [comment] 2021-08-03 08:50
The start.sh: https://hastebin.com/mapifomezo.kotlin

**Comment by hardillb** [comment] 2021-08-03 09:04
OK, So that all works fine.

The error is because Node-RED is trying to copy the standard `settings.js` into `/data` because it can't find one at startup which implies that there is different problem with either the mount or what you are copying into it.

I suggest you add the following to the beginning of the `start.sh`

```
ls -ld /data
ls -l /data
```
This should show the permissions on the mounted volume and it's content before you try to start Node-RED

**Comment by TimoB2005** [comment] 2021-08-03 09:11
i added that to my start.sh but it doesnt change anything.
start.sh: https://hastebin.com/yozenidobo.kotlin

**Comment by hardillb** [comment] 2021-08-03 09:12
It's not going to change anything, but it should log the ls output before trying to start Node-RED

**Comment by TimoB2005** [comment] 2021-08-03 09:14
![image](https://user-images.githubusercontent.com/83423736/127990611-eab897e6-716a-41ab-93f6-1175fab0ec69.png)
Don't works for me?

**Comment by hardillb** [comment] 2021-08-03 09:16
You've missed off the lines before that which is where the output would be.

Also have you forced a rebuild of the container before trying to restart the compose to make sure it's picked up the changed start.sh?

**Comment by TimoB2005** [comment] 2021-08-03 09:17
i forgot to build i am sorry.

output: 
![image](https://user-images.githubusercontent.com/83423736/127991040-fdf2b52b-3e94-4276-ad68-dd7207c93817.png)

**Comment by hardillb** [comment] 2021-08-03 09:18
There is your problem, data is not owned by 1000:1000

**Comment by TimoB2005** [comment] 2021-08-03 09:19
How do i fix that?

**Comment by TimoB2005** [comment] 2021-08-03 09:23
Now the copy error is gone but an other error with open a sqlite file is there

**Comment by hardillb** [comment] 2021-08-03 09:26
Without full access to your environment to have a proper look I can't say. It looks like you've messed up the volume mounts some how.

But if Node-RED is starting correctly and it's just your sqlite stuff that isn't working I'm going to close this issue as it's not a Node-RED problem. You can try asking on the forum to see if anybody can help.

**Closed by hardillb** 2021-08-03 09:26 UTC

**Comment by TimoB2005** [comment] 2021-08-03 10:01
i did delete my sqlstuff and my error shows up again...
